* ET-232 Protocol Documentation
** Introduction

This document is a specification for the serial communications
protocol of the ET232 Electrostimulation box by Erostek. The protocol
was put together through information found around the internet. 

Note that the information in this document has yet to be tested, and
therefore may be incorrect in some places. If you find any issues,
please [[http://github.com/metafetish/erosoutsider/issues][file issues in our github repo]].
** Communication via Link Cable
Communicating with the ET-232 box happens via an RS-232 Connection to
the Link port of the box. The link cable consists of a 3.5mm TRS
(stereo audio) jack, going to some sort of computer connection, be it
Female DB-9 or a RS232-to-USB converter. The pin connections are as
follows:

- 3.5mm Tip <-> RX (DB-9 Pin 2)
- 3.5mm Ring <-> TX (DB-9 Pin 3)
- 3.5mm Sleeve <-> Ground (DB-9 Pin 5)

Serial connections are 19200/8/N/1, or:

- 19200 baud
- Data Bits: 8
- Stop Bits: 1
- Partity: None

To use the serial link on the ET-232, the cable must be plugged in
before the box is turned on, in order to complete the handshake
protocol. Otherwise, the jack will register as an audio input jack.
Similarly, to use the jack as audio once again, the box should be
turned off and back on first, in order to reestablish audio mode.
** Handshake
When the box is powered on, the ET-232 will send a single byte:

#+BEGIN_EXAMPLE
0xcc
#+END_EXAMPLE

Assuming this is transferred correctly, the box then listens for and
responds to commands. Unlike the ET-312, the ET-232 does not use an
encrypted protocol.

** Commands
*** Format
Commands consist:

- ASCII characters
- A 2-byte checksum _string_, meaning two ASCII uppercase characters
  representing one hex byte. The checksum is a sum of all the
  characters in the range from '0' (0x30) to 'Z' (0x90) in the string.
  All characters outside of this range are ignored for the purposes of
  the checksum. This would be output by using a "%02X" printf-style
  formatter, for instance.
- A "\r" character to end the command.

Valid commands will be acknowledged with the following string:

#+BEGIN_EXAMPLE
\n
#+END_EXAMPLE

If a command is unrecognized, or the checksum does not match, the
following string will be returned:

#+BEGIN_EXAMPLE
?\r\n
#+END_EXAMPLE

*** Commands

Commands work on a peek and poke basis, similar to the ET-312.

**** Read Byte ("H")

Reading a byte from the ET-232 is done using the "H" command.
This command consists of:

- "H" (0x48)
- A 8-bit address, written as 2 ASCII characters representing the hex
  value.
- The checksum
- "\r"

For instance, to read the byte at 0x80 (which gives you a checksum of 0xB0), you would send

#+BEGIN_EXAMPLE
H80B0\r
#+END_EXAMPLE

The command will return a two digit hex value at the requested
location, in ASCII format.

**** Write Byte ("I")

Writing a byte from the ET-232 is done using the "I" command.
This command consists of:

- "I" (0x49)
- A 8-bit address, written as 2 ASCII characters representing the hex
  value.
- An 8-bit value, written as 2 ASCII characters representing the hex
  value.
- The checksum
- "\r"

For instance, to write the value 0x10 to the byte at 0x80 (which gives
you a checksum of 0x12), you would send

#+BEGIN_EXAMPLE
I801012\r
#+END_EXAMPLE

The command, if successful, will return the string "$\n"

**** Unknown ("J")

The usage of the "J" command is unknown. Sending "J" appears to ignore
arguments and returns "FF\n"

** Address Table

| Address | Description                          |
|---------+--------------------------------------|
| $08     | Channel A Pulse Width                |
| $09     | Channel A Pulse Frequency Reciprocal |
| $0A     | Channel A Pulse Amplitude            |
| $0B     | Channel A Power Compensation         |
| $0C     | Channel A Pulse Enable Polarity      |
| $0D     | ??                                   |
| $0E     | Channel B Pulse Width                |
| $0F     | Channel B Pulse Frequency Reciprocal |
| $10     | Channel B Pulse Amplitude            |
| $11     | Channel B Power Compensation         |
| $12     | Channel B Pulse Enable Polarity      |
| $13-1F  | ??                                   |
| $20-4F  | RAM/Program Parameters?              |
| $4F-87  | ??                                   |
| $88     | Position of Pot B                    |
| $89     | Position of MA Pot                   |
| $8A     | Battery Voltage                      |
| $8B     | Audio Input Level                    |
| $8C     | Position of Pot A                    |
| $8D-97  | ??                                   |
| $98     | Position of MA Pot (?)               |
| $99-A1  | ??                                   |
| $A2     | Mode Switch Position                 |
| $A3     | Mode Switch Override                 |
| $A4     | Analog Input Override                |
| $A5-CF  | ??                                   |
| $D0     | Unknown Timer                        |
| $D1     | Unknown Timer                        |
| $D2     | ??                                   |
| $D3     | Auto Power Off Timer                 |
| $D8     | Program Fade In Timer                |
| $D9-FB  | ??                                   |
| $FC     | Unknown Timer                        |
| $FD     | Unknown Timer                        |
| $FE-FF  | ??                                   |

